### ISSUE TITLE
Empatica Data capture

### ISSUE THREAD

**Issue by raheelsayeed** [RADAR-CNS/RADAR-Android-Empatica#14]
Hi, I've got a question regarding the workflow for emphatic data capture. 

I was wondering, How radar accesses the data through Empatica's Android SDK. As far as I can tell, it does allow "Live streaming". I was interested to know if theres a webapi that allows fetching of 24 hr recorded data (either direct via BLE or online at empatica cloud)

**Comment by blootsvoets** [comment]
In RADAR-base, the data from the Empatica E4 is collected via live streaming in the [RADAR pRMT Android app](https://github.com/radar-base/radar-prmt-android). The data is then transferred to the main [RADAR platform](https://github.com/radar-base/radar-docker). That platform aggregates data into hourly files, but it does not allow API access to the raw data, although that [is a potential feature](https://github.com/RADAR-base/RADAR-RestApi/issues/71).

We are not affiliated with Empatica, so I cannot comment on the functionality that [Empatica](https://empatica.com) offers.

**Comment by raheelsayeed** [comment]
@blootsvoets Thanks for the reply and clarity. Its great that RADAR platform can create smaller chunks. I have one more question on the live streaming capture: in your experience, has the live streaming been reliable enough to capture hours of continuous recording on a smartphone app (iOS/Android)?

**Comment by blootsvoets** [comment]
Regarding live streaming, I think there were some issues there, especially in a home setting. Perhaps @yatharthranjan or @sboettcher could you comment?

**Comment by raheelsayeed** [comment]
Would be great to know more, we are looking to do something similar – home/ipatient setting with continuous recording. It became a little less practical though, instead we just downloaded data from the E4.

**Comment by yatharthranjan** [comment]
From my experience live streaming works fine as long as the passive app is in the foreground. As soon as the app goes in background, empatica disconnects causing it to turn off, then we have to manually turn it on to reconnect it. This is thus not ideal for the remote data collection in the current state but it works quite well in in-hospital setting where the app runs in foreground all the time on a tablet. WE have hours of continuous data from empatica. 

Note: We haven't maintained the empatica plugin for a while now (as its not being used in any remote monitoring studies) so that could be the reason is why its not working properly with the latest version of the app. Empatica have also release v0.2.2 of their SDK in April 2018 so might get better results with that.

**Comment by raheelsayeed** [comment]
@yatharthranjan thanks for the replying. We have similar findings. We used latest iOS SDK. For in-hospital– live streaming is well supported, as you said, if an an app is run in a kiosk mode (active and wired all the time). 

Ideally, would have worked great if E4 allowed downloading of saved data. Oh well.
